version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "score-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10c6c6nd180n0"
s3_prefix = "score-api"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
